steps:
  - label: ":test_tube: Testing system output"
    command: "uname"
  - label: ":test_tube: perform local testing here"
    command: "sleep 300"
    agents:
      image: "docker.elastic.co/ci-agent-images/ci-systems/cdktf:1.1"
  - label: "Test Terraform pipeline Staging :congratulations: :terraform:"
    command:
      - .buildkite/scripts/vault-auth-lookup.sh
      - .buildkite/scripts/plan.sh workspaces/staging
    agents:
      image: "docker.elastic.co/ci-agent-images/ci-systems/cdktf:1.1"
  - label: "Test Terraform pipeline Production :congratulations: :terraform:"
    command:
      - .buildkite/scripts/plan.sh workspaces/production
    agents:
      image: "docker.elastic.co/ci-agent-images/ci-systems/cdktf:1.1"
