agents:
  queue: kubernetes

steps:
  - label: "Test pipeline :congratulations: :champagne:"
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest
                command: [uname]