steps:
  - label: "Test pipeline :congratulations: :champagne:"
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest
                command: [uname]