steps:
  - label: ":test_tube: Testing system output"
    command: "uname"
  - label: "Test Terraform pipeline :congratulations: :terraform:"
    command: "terraform version"
    agents:
      image: "docker.elastic.co/ci-agent-images/infra-foundations/go-builder-buildkite-agent:0.0.1"
