steps:
  - label: ":test_tube: Testing system output"
    command: "uname"
  - label: "Test Terraform pipeline :congratulations: :terraform:"
    command: "terraform version"
    agents:
      image: "docker.elastic.co/ci-agent-images/ci-systems/cdktf:1.1"
