agents:
  queue: kubernetes

steps:
  - label: "Test Terraformt pipeline :congratulations: :terraform:"
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: hashicorp/terraform:1.7.3
                command: [terraform,version]
