agents:
  queue: kubernetes

steps:
  - label: "Test Terraform pipeline :congratulations: :terraform:"
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: hashicorp/terraform:1.7.3
                name: terraform-plan
                command:
                  - .buildkite/scripts/plan.sh
                  - workspaces/staging